<script>
    try{
        let res=someUndefinedFunction()
    }
    catch(error){
        document.write("An error occured: ",error.message)
    }
    finally{
        document.write(" End")
    }
</script>